version: "3.5"
services:
  mysql:
    image: mysql:8.0.32
    command: --lower_case_table_names=1
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: IceHrmR00t
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
      MYSQL_DATABASE: icehrm
    volumes:
      - ./docker/init.sql:/docker-entrypoint-initdb.d/setup.sql
      - ./docker/development/db_data:/var/lib/mysql

  icehrm:
    build: .
    ports:
      - 9080:8080
    environment:
      ICE_CONFIG_FILE: ../docker/development/config/config.php
    volumes:
      - .:/var/www/html

  icehrm-worker-dev:
    build:
      context: ./
      dockerfile: Dockerfile-worker
      args:
        - EXE_ENV=development

  phpmyadmin-dev:
    depends_on:
      - mysql
    image: phpmyadmin
    ports:
      - "9081:80"
    environment:
      PMA_HOSTS: mysql
      PMA_PORT: 3306
      PMA_USER: dev
      PMA_PASSWORD: dev

  mailhog:
    image: ajoergensen/mailhog
    ports:
      - "1025:1025"
volumes:
  db_data:
