version: "3.5"
services:
  mysql-prod:
    image: mysql:5.7
    ports:
      - 3129:3306
    environment:
      MYSQL_ROOT_PASSWORD: IceHrmR00t
      MYSQL_USER: prod
      MYSQL_PASSWORD: prod
      MYSQL_DATABASE: icehrm
    volumes:
      - ./docker/init.sql:/docker-entrypoint-initdb.d/setup.sql
      - ./docker/prod/db_data:/var/lib/mysql

  icehrm-prod:
    build:
      context: ./
      dockerfile: Dockerfile-prod
    ports:
      - 3128:8070
    volumes:
      - ./docker/prod/app_data:/var/www/html/app/data

  icehrm-worker:
    build:
      context: ./
      dockerfile: Dockerfile-worker
      args:
        - EXE_ENV=prod

  phpmyadmin:
    depends_on:
      - mysql-prod
    image: phpmyadmin
    ports:
      - "3130:80"
    environment:
      PMA_HOSTS: mysql-prod
      PMA_PORT: 3129
      PMA_USER: prod
      PMA_PASSWORD: prod

volumes:
  db_data:
  app_data:
